version: '3'
services:
  loader:
    build: .
    environment:
        #SCALE FACTOR (in GB), 0.1 for 100 MB
        - SCALE=1
        - GCS_URL=gs://XXXX/bulk-load
        - PROJECT=XXX
        - DATASET=tpcds_full
        - PARALLELISM=4
    volumes:
        - ${GOOGLE_APPLICATION_CREDENTIALS}:/serviceaccount.json